ARG NODE_TAG=12
ARG APP_HOME=/home/node/app

FROM node:${NODE_TAG}
ARG NODE_TAG
ARG APP_HOME

WORKDIR ${APP_HOME}
COPY package*.json ${APP_HOME}/
RUN npm install --production

COPY src ${APP_HOME}/src/
COPY public ${APP_HOME}/public/
RUN npm run build

EXPOSE 5000

RUN npm install serve -g

CMD [ "serve", "-s", "./build" ]